feat: sast ci及nsh替换暂存

diff --git a/.github/workflows/build-multi-irify-prod.yml b/.github/workflows/build-multi-irify-prod.yml
--- a/.github/workflows/build-multi-irify-prod.yml
+++ b/.github/workflows/build-multi-irify-prod.yml
@@ -1,4 +1,4 @@
-name: Build Multi-Sast-Platform Prod
+name: Build Multi-IRify-Platform Prod
 
 on:
     workflow_dispatch:
@@ -19,8 +19,8 @@ jobs:
             - name: Check if the version number is correct
               run: |
                   VERSION_INPUT=$GITHUB_REF_NAME
-                  if [[ $VERSION_INPUT != v*-sast ]]; then
-                    echo "Error: Version must start with 'v' and end with '-sast'." >&2
+                  if [[ $VERSION_INPUT != v*-irify ]]; then
+                    echo "Error: Version must start with 'v' and end with '-irify'." >&2
                     exit 1
                   else
                     echo "Version starts with 'v': $VERSION_INPUT"
@@ -86,7 +86,7 @@ jobs:
               run: |
                   ENV_TAG=${{ github.ref_name }}
                   ENV_TAG=${ENV_TAG#v}
-                  ENV_TAG=${ENV_TAG%-sast}
+                  ENV_TAG=${ENV_TAG%-irify}
                   echo "ENV_TAG=$ENV_TAG" >> $GITHUB_ENV
               shell: bash
 
@@ -95,14 +95,14 @@ jobs:
               name: "Install Dependencies"
 
             - name: Build pre script
-              run: chmod +x ./packageScript/script/buildPreScript.sh && ./packageScript/script/buildPreScript.sh sast
+              run: chmod +x ./packageScript/script/buildPreScript.sh && ./packageScript/script/buildPreScript.sh irify
               shell: bash
 
             - name: Build IRify Normal And Legacy (MultiPlatform)
               env:
                   GH_TOKEN: ${{ secrets.GH_TOKEN }}
               working-directory: ./
-              run: ./packageScript/script/electron-sast-builder.sh sast || { exit 1; }
+              run: ./packageScript/script/electron-irify-builder.sh irify || { exit 1; }
               shell: bash
 
             - name: View Published Content
@@ -128,7 +128,7 @@ jobs:
               env:
                   GH_TOKEN: ${{ secrets.GH_TOKEN }}
               working-directory: ./
-              run: ./packageScript/script/electron-sast-builder.sh sastee || { exit 1; }
+              run: ./packageScript/script/electron-irify-builder.sh irifyee || { exit 1; }
               shell: bash
 
             - name: View Published Content
@@ -162,7 +162,7 @@ jobs:
               run: |
                   ENV_TAG=${{ github.ref_name }}
                   ENV_TAG=${ENV_TAG#v}
-                  ENV_TAG=${ENV_TAG%-sast}
+                  ENV_TAG=${ENV_TAG%-irify}
                   echo "ENV_TAG=$ENV_TAG" >> $GITHUB_ENV
 
             - name: Download IRify And Legacy IRify
@@ -177,7 +177,7 @@ jobs:
             - name: Generate OSS File Path
               run: |
                   if [ "${{ matrix.artifact }}" = "IRify" ]; then
-                    echo "FILE_PATH=sast" >> $GITHUB_ENV
+                    echo "FILE_PATH=irify" >> $GITHUB_ENV
                   elif [ "${{ matrix.artifact }}" = "IRifyEnterprise" ]; then
                     echo "FILE_PATH=svip" >> $GITHUB_ENV
                   else
