feat: ci及细节完善

diff --git a/.github/workflows/build-multi-sast-prod.yml b/.github/workflows/build-multi-sast-prod.yml
--- a/.github/workflows/build-multi-sast-prod.yml
+++ b/.github/workflows/build-multi-sast-prod.yml
@@ -1,9 +1,7 @@
 name: Build Multi-Sast-Platform Prod
 
 on:
-    push:
-        tags:
-            - "v*-sast"
+    workflow_dispatch:
 
 jobs:
     build_yakit:
@@ -18,6 +16,16 @@ jobs:
             CERT_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
 
         steps:
+            - name: Check if the version number is correct
+              run: |
+                  VERSION_INPUT=$GITHUB_REF_NAME
+                  if [[ $VERSION_INPUT != v*-sast ]]; then
+                    echo "Error: Version must start with 'v' and end with '-sast'." >&2
+                    exit 1
+                  else
+                    echo "Version starts with 'v': $VERSION_INPUT"
+                  fi
+
             - uses: actions/checkout@v4
             - uses: actions/setup-node@v4
               with:
@@ -76,9 +84,10 @@ jobs:
 
             - name: Echo SastScan Package Version To Env
               run: |
-                ENV_TAG=${GITHUB_REF_NAME:1}
-                ENV_TAG=${ENV_TAG%-sast}
-                echo "ENV_TAG=$ENV_TAG" >> $GITHUB_ENV
+                  ENV_TAG=${{ github.ref_name }}
+                  ENV_TAG=${ENV_TAG#v}
+                  ENV_TAG=${ENV_TAG%-sast}
+                  echo "ENV_TAG=$ENV_TAG" >> $GITHUB_ENV
               shell: bash
 
             - run: yarn install
@@ -150,7 +159,11 @@ jobs:
         runs-on: ubuntu-latest
         steps:
             - name: Echo Package Version To Env
-              run: echo "ENV_TAG=${GITHUB_REF_NAME:1}" >> $GITHUB_ENV
+              run: |
+                  ENV_TAG=${{ github.ref_name }}
+                  ENV_TAG=${ENV_TAG#v}
+                  ENV_TAG=${ENV_TAG%-sast}
+                  echo "ENV_TAG=$ENV_TAG" >> $GITHUB_ENV
 
             - name: Download SastScan And Legacy SastScan
               uses: actions/download-artifact@v4
@@ -160,15 +173,6 @@ jobs:
 
             - run: ls
               name: Ls Published Artifacts...
-
-            - name: Create Release and Upload Assets
-              if: ${{ matrix.artifact == 'SastScan' }}
-              uses: ncipollo/release-action@v1
-              with:
-                  artifacts: ./*
-                  token: ${{ secrets.GITHUB_TOKEN }}
-                  name: Release ${{ github.ref_name }}
-                  tag: ${{ github.ref_name }}
 
             - name: Generate OSS File Path
               run: |
